# Generated by Django 3.2.4 on 2021-06-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
