# Generated by Django 3.2.8 on 2021-10-30 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211030_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='Ngo_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
